# general setting
batch_size: 16
input_size: 320
sub_name: 'retinaface_mbv2'
weights: './model/mobilenet_v2_weights_tf_dim_ordering_tf_kernels_1.0_224_no_top.h5'

# training dataset
dataset_path: './data/widerface_train_bin_10000.tfrecord'
dataset_len: 10000
using_bin: True
using_flip: False
using_distort: False

# testing dataset
testing_dataset_path: '/Users/lichaochao/Downloads/CelebA/CelebA/test/'

# network
out_channel: 64

# anchor setting
min_sizes: [[16, 32], [64, 128], [256, 512]]
steps: [8, 16, 32]
match_thresh: 0.5
ignore_thresh: 0.3
variances: [0.1, 0.2]
clip: False

# training setting
epoch: 100
init_lr: !!float 1e-2
lr_decay_epoch: [50, 68]
lr_rate: 0.1
warmup_epoch: 5
min_lr: !!float 1e-3

weights_decay: !!float 5e-4
momentum: 0.9

pretrain: True

save_steps: 1000
